# We test each method for building LaTeX in a separate job.
jobs:
  include:
    # Each script call is a separate job.
    - script: chmod +x $TRAVIS_BUILD_DIR/test/compile-1.sh && $TRAVIS_BUILD_DIR/test/compile-1.sh
      cache:
        directories:
          - $HOME/miniconda
          - $HOME/.cache/Tectonic
    - script: chmod +x $TRAVIS_BUILD_DIR/test/compile-2.sh && $TRAVIS_BUILD_DIR/test/compile-2.sh
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
    - language: r
      sudo: true
      latex: false
      pandoc: false
      warnings_are_errors: false
      install: echo "The install step is required but does nothing now."
      script: chmod +x $TRAVIS_BUILD_DIR/test/compile-3.sh && $TRAVIS_BUILD_DIR/test/compile-3.sh
      cache:
        directories:
          - packages
          - /tmp/texlive
          - $HOME/.texlive
          - $HOME/.TinyTex
